### ISSUE TITLE
Type script files

### ISSUE THREAD

**Issue by rameshbas** [OnsenUI/angular2-onsenui-kitchensink#1]
is this where I can see the app is created using Typescript? Only .js files are there. Where are the .ts files?

**Comment by masahirotanaka** [comment]
Hi @rameshbas. Yes, TypeScript files are contained in `src/app` directory, and they will be transpiled to `.js` files when the application is actually executed. See our TypeScript code here:

https://github.com/OnsenUI/angular2-onsenui-kitchensink/tree/master/src/app

**Comment by rameshbas** [comment]
Thx. It is there! How do you build ask files now? Monaca debug?Or monaca run android?

**Comment by masahirotanaka** [comment]
Yes, you should be able to build apk package by running `monaca remote build` command.
It will guide you to the browser to complete the build process.

**Comment by IliaSky** [comment]
Since the initial question here (whether this app is created using typescript) has been answered I am closing this issue. The second question's discussion can be found at #2.
